# Generated by Django 2.1.7 on 2019-03-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_auto_20190217_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='activation_key',
        ),
        migrations.RemoveField(
            model_name='shopuser',
            name='activation_key_expires',
        ),
    ]
