# Generated by Django 2.1.7 on 2019-03-18 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_auto_20190317_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuserprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shopuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='shopuser',
            name='avatar',
        ),
        migrations.DeleteModel(
            name='ShopUserProfile',
        ),
    ]
